---
# Nginx Service stop and start
- name: nginx stop
  service:
    name: nginx
    state: stopped
  tags:
    - nginx-stop

- name: nginx start
  service:
    name: nginx
    state: started
  tags:
    - nginx-start

- name: nginx restart
  service:
    name: nginx
    state: restarted
  tags:
    - nginx-restart