---
# etl deployment
- name: ensure etl directory is on etl server
  file:
    path: "{{ etl_base_path }}/webapps"
    state: directory

- name: ensure etl backup directory is on etl server
  file:
    path: "{{ backup_path }}"
    state: directory

#- name: taking the backup of webapps directory.
#  shell: "mv {{ etl_base_path }}/webapps {{ backup_path }}/webapps_$(date +%d-%m-%Y_%H-%M-%S)"

- name: create etl and etl.war directory in tomcat
  file:
    path: "{{ etl_base_path }}/webapps/etl"
    state: absent
- name: create etl and etl.war directory in tomcat
  file:
    path: "{{etl_base_path}}/webapps/etl.war"
    state: absent

- name: unzip artifact
  unarchive:
    src: "{{ artifact_path }}"
    dest: "{{ etl_base_path }}/webapps"
    remote_src: yes
