---
- name: install perl packages.
  package:
    name: "{{ item }}"
    state: present
  loop:
    - perl-Switch
    - perl-DateTime
    - perl-Sys-Syslog
    - perl-LWP-Protocol-https
    - perl-Digest-SHA.x86_64
    - zip
    - unzip

- block:
  - name: delete directory
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/tmp/aws-mon/instance-id
      - ~/aws-scripts-mon/

  - name: unarchive zip.
    unarchive:
      src: "{{ artifact }}"
      dest: ~/
      remote_src: yes
  - name: create credentials
    shell: printf "%s\n" "AWSAccessKeyId={{ access }}" "AWSSecretKey={{ secret }}" > ~/aws-scripts-mon/awscreds.conf

  - name: creating cron job.
    cron:
      name: "cloud watch for memory metrics"
      minute: "*/5"
      job: "~/aws-scripts-mon/mon-put-instance-data.pl --mem-util --mem-used --mem-avail --swap-util --from-cron"
  become_user: taxadmin