---
#user stop
- name: Get running processes list from remote host
  ignore_errors: yes
  shell: "ps -eaf | grep /opt/user/ | awk -F' ' '{print $2}' | xargs kill -9"
  #register: running_processes

#- name: Kill running processes
#  ignore_errors: yes
#  shell: "kill {{ item }}"
#  with_items: "{{ running_processes.stdout_lines }}"
 
#- wait_for:
#    path: "/proc/{{ item }}/status"
#    state: absent
#  with_items: "{{ running_processes.stdout_lines }}"
#  ignore_errors: yes
#  register: crunchify_processes
 
#- name: Force kill stuck processes
#  ignore_errors: yes
#  shell: "kill -9 {{ item }}"
#  with_items: "{{ crunchify_processes.results | select('failed') | map(attribute='item') | list }}"