- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Add Unix Admins users
  user: name={{ item }} groups=wheel
  with_items: "{{ users }}"

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'