---
#vdm deployment
- block:
  - name: ensure webapps directory is on vdm server
    file:
      path: "{{ base_path }}/webapps"
      state: directory

  - name: ensure etl backup directory is on etl server
    file:
      path: "{{ backup_path }}"
      state: directory

  - name: taking the backup of webapps directory.
    shell: "mv {{ base_path }}/webapps {{ backup_path }}/webapps_$(date +%d-%m-%Y_%H-%M-%S)"

  - name: create webapps directory in tomcat
    file:
      path: "{{ base_path }}/webapps"
      state: directory

  - name: unzip artifact
    unarchive:
      src: "{{ artifact_path }}"
      dest: "{{ base_path }}/webapps"
  become: yes
  become_user: "{{ user }}"

#- name: mv etl.war to root.war
#  command: mv "{{ base_path }}/webapps/etl.war" "{{ base_path }}/webapps/root.war"