---
# user deployment
- name: ensure eninvoice directory is on eninvoice server
  file:
    path: "{{ eb_base_path }}/eninvoice"
    state: directory

- name: ensure user backup directory is on eninvoice server
  file:
    path: "{{ backup_path }}"
    state: directory

  #- name: taking the backup of eninvoice folder
  #shell: "mv {{ eb_base_path}}/eninvoice {{ backup_path }}/eninvoice_$(date +%d-%m-%Y_%H-%M-%S)"

- name: remove the eninvoice folder
  file:
    path: "{{eb_base_path}}/eninvoice"
    state: absent

- name: unzip artifact
  unarchive:
    src: "{{ eb_artifact_path }}"
    dest: "{{ eb_base_path }}"
    remote_src: yes
